version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "WB_developer"
      POSTGRES_USER: "mbatimel"
      POSTGRES_PASSWORD: "wb_il"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: "WB_developer"
      POSTGRES_USER: "mbatimel"
      POSTGRES_PASSWORD: "wb_il"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"

volumes:
  postgres-data:
