version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "WB_developer"
      POSTGRES_USER: "mbatimel"
      POSTGRES_PASSWORD: "wb_il"
    ports:
      - "5432:5432"